name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: |
          mkdir -p build
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/webdebugger-${{ matrix.goos }}-${{ matrix.goarch }}$ext
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webdebugger-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/webdebugger-${{ matrix.goos }}-${{ matrix.goarch }}*
